### ISSUE TITLE
Review of structure

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/PhD-Thesis#1]
@mielvds @RubenVerborgh Could you do an initial review of my current structure?

**Comment by RubenVerborgh** [comment]
Structure looks good, I like how things are woven together.

Maybe move the current Chapter 2 after 4? First have data, then query it? Then there's a nice progression to 5.

"Generating Evolving Data" => I'm missing in that chapter title that it is for testing purposes. Maybe "Testing Evolving Data [Solutions]' or similar?

**Comment by mielvds** [comment]
Yes, the red lin is pretty much on point. I like how the intro comes in, but of course needs some more fine tuning. 
About the RQ, I wonder  if "How to store and query evolving knowledge graphs on the Web?" sufficiently acknowledges the existing work. In some way, you could already do this, but you progressed the techniques. Or maybe you should stress the fact that you looked into making them more _Web_by. 

> Structure looks good, I like how things are woven together.
> 
> Maybe move the current Chapter 2 after 4? First have data, then query it? Then there's a nice progression to 5.

+1

> 
> "Generating Evolving Data" => I'm missing in that chapter title that it is for testing purposes. Maybe "Testing Evolving Data [Solutions]' or similar?

I think adding the word synthetic somewhere would do it, because this implies testing.

**Comment by rubensworks** [comment]
Thanks for the feedback!
